<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\RedirectCommand;
/**
 * Implements hook_form_FORM_ID_alter().
 */
function atom8_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {


        if (isset($form['revision_information'])) {
        $form['revision_information']['#access'] = FALSE;
        }
        unset($form['footer']);
        unset($form['meta']);
        unset($form['options']);
        unset($form['advanced']);

        $form['actions']['delete']['#attributes']['class'][] = 'flex-1 flex items-center justify-center w-full px-4 py-2 text-sm font-medium leading-5 text-white text-gray-700 transition-colors duration-150 border border-gray-300 rounded-lg dark:text-gray-400 active:bg-transparent hover:border-gray-500 focus:border-gray-500 active:text-gray-500 focus:outline-none focus:shadow-outline-gray';



}
